language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
before_install:
  - set -e
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo fmt -- --check
  - rustup self update
script:
  - cargo fmt -- --check
  - cargo clippy -- -D all
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
