[package]
name = "click"
version = "0.3.0"
authors = ["Nick Lanham <nick@afternight.org>"]
homepage = "https://github.com/databricks/click/wiki"
repository = "https://github.com/databricks/click"
license = "Apache-2.0"

[dependencies]
ansi_term = "0.9"
base64 = "0.5"
chrono = { version = "0.3", features = ["serde"] }
clap = "2.22"
ctrlc = "3.0"
der-parser = "0.3"
duct = "^0.9"
duct_sh = "^0.1"
fd = "^0.2"
humantime = "1.0"
hyper = "0.10"
hyper-rustls = "0.3"
lazy_static = "0.2"
openssl = "^0.10"
prettytable-rs = "^0.6"
regex = "0.2"
rustls = "0.5"
rustyline = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
term = "^0.4"